### PR TITLE
Add modules

### PR DESCRIPTION
**Pull request by vanillainanutshell**
# What was done in this PR:

- Add modules folder;
- Separated index.js on files inside modules;

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED 🔴 🛑
Hello @vanillainanutshell, @denscholar, and @sumairq  great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Your repo is professional 
- Your project is professional 
- Well structured files 

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️

- [ ] It would be better if you use the [Luxon](https://moment.github.io/luxon/#/install) library to get the current time. Kindly add this library and use it to get the current time. 

Capture


Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

cat


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by denscholar** [comment]
@BrianSammit and @vanillainanutshell Honestly, I am surprised why I was tagged to this repo when this project is not a collaborative project. Please, can anyone explain why this happened?

**Comment by vanillainanutshell** [comment]
> @BrianSammit and @vanillainanutshell Honestly, I am surprised why I was tagged to this repo when this project is not a collaborative project. Please, can anyone explain why this happened?

I actually have no idea

**Review by rustam-tolipov — APPROVED** [review]
## Hi @vanillainanutshell 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

image

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
